// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  author: dynamic(() => import("./Author")),
  footer: dynamic(() => import("./Footer")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  latest_blogs: dynamic(() => import("./LatestBlogs")),
  tech_stack: dynamic(() => import("./TechStack")),
};
